# Generated by Django 4.0.1 on 2022-01-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_time_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='home',
            field=models.CharField(choices=[('서울', '서울'), ('인천', '인천'), ('경기', '경기'), ('강원', '강원'), ('충청', '충청'), ('세종', '세종'), ('대전', '대전'), ('경상', '경상'), ('대구', '대구'), ('전라', '전라'), ('울산', '울산'), ('부산', '부산'), ('제주', '제주'), ('광주', '광주')], max_length=30, verbose_name='집'),
        ),
        migrations.AlterField(
            model_name='user',
            name='how',
            field=models.TextField(verbose_name='어떻게 알게되었는가'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='이름'),
        ),
    ]
