# Generated by Django 3.2.9 on 2021-12-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_report', '0002_alter_errorreport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='error_image/'),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='how',
            field=models.TextField(blank=True, null=True),
        ),
    ]
