# Generated by Django 3.2.9 on 2021-11-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
