# Generated by Django 3.2.9 on 2021-12-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_report', '0003_auto_20211220_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
